server:
  port: 8090
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  freemarker:
    check-template-location: false
  thymeleaf:
    cache: false
    mode: HTML5
  datasource:
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sudo_security?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
  #redis 配置
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    #password: 123456
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 16
        #连接池中的最大空闲连接
        min-idle: 8
        #连接池中的最小空闲连接
        max-wait: 0
    #连接超时时间（毫秒）
    timeout: 300000
    database: 0
  cache:
    type: redis # 指定使用的缓存类型
